baseURL = 'https://aosjmi.github.io'
languageCode = 'ja-jp'
title = 'Blog'
canonifyURLs = true

[params]
  mainSections = ["posts"]
[content]
  blog = "content/posts"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  paginate = 10
  
[permalinks]
  posts = "/:year/:month/:title/"
